// Generated by Copilot
// Log Analytics workspace module - equivalent to nested deployment in ARM template

param workspaceName string
param location string

resource logAnalyticsWorkspace 'Microsoft.OperationalInsights/workspaces@2021-06-01' = {
  name: workspaceName
  location: location
  properties: {}
}

output workspaceId string = logAnalyticsWorkspace.id
