# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: 'Use Node 18.x'
  inputs:
    versionSpec: 18.x
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  displayName: Archive Angular Build
  inputs:
    rootFolderOrFile: www
    includeRootFolder: false

- task: CopyFiles@2
  inputs:
    SourceFolder: '.azure/ARMTemplates'
    Contents: 'azuredeploy*.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    FileCopyOptions: ''

